	<div id="footer" >
		<span class="level_one">
			<!-- <ul>
				<li>Home</li>
				<li>Whatever</li>
			</ul> -->
		</span>		
		<div class="standards" >		
			<a href="http://validator.w3.org/check?uri=referer">
				<img src="<?php echo base_url(); ?>assets/images/valid-xhtml10.png" alt="Valid XHTML 1.0 Transitional"  />
			</a>
		</div>
		<div class="noteproper" >		
			<p>&copy; Copyright 2011-2012 Abraham Darius Llave unless otherwise noted.</p>
			<p>Made in partial fulfillment for the requirements of the degree Bachelor of Science in Computer Science</p>
		</div>
	</div>
