<div id="basic-modal-content-freeform" >
	<input type="hidden" name="uniqueID" id="seatMapUID" value="0" />
	<input type="hidden" name="seatMap_isMaster" id="seatMap_isMaster_indicator value="0" />
	<div id="SeatV2Title" >
		<span id="titleProper" >Choose seat <!--for <span id="eventName"></span>--></span>
		<span class="eventWhen" ></span>
		<span id="place" ></span>
	</div>	
	<div id="warningIndicator" ></div>
	<div id="seatSelectionLegend"  >
		<span id="available" > Available / Still unassigned </span>	
		<span class="otherGuest" >  Assigned seats for other guests under this boooking </span>
		<span id="assigned" > Your seat </span>
		<span class="occupiedSameClass" >Occupied</span>
		<span class="classRestricted">Seats for other classes</span>
	</div>				
	<div id="seatSelectionTable"  class="center_purest">
		
	</div>		
	<div id="overlayV2ButtonsArea" >							
							<a class="button overlayV2Button" id="overlayV2Button_OK" ><span class="icon">okay</span></a>																					
	</div>	
</div>