	<script type="text/javascript" src="<?php echo base_url().'assets/jquery/jquery.ui.widget.js'; ?>"></script>
	<script type="text/javascript" src="<?php echo base_url().'assets/jquery/jquery.ui.mouse.js'; ?>"></script>
	<script type="text/javascript" src="<?php echo base_url().'assets/jquery/jquery.ui.position.js'; ?>"></script>
	<script type="text/javascript" src="<?php echo base_url().'assets/jquery/jquery.ui.draggable.js'; ?>"></script>
	<script type="text/javascript" src="<?php echo base_url().'assets/jquery/jquery.ui.droppable.js'; ?>"></script>
	<script type="text/javascript" src="<?php echo base_url().'assets/jquery/jquery.ui.resizable.js'; ?>"></script>
	<script type="text/javascript" src="<?php echo base_url().'assets/jquery/jquery.ui.selectable.js'; ?>"></script>
	<script type="text/javascript" src="<?php echo base_url().'assets/jquery/jquery.ui.sortable.js' ?>"></script>
	<!-- This plugin sourced from http://plugins.scbfolio.com/jquery_drag_drop_select/ (c) 2012 Samuel Cléroux-Bouthillier --> 
	<script type="text/javascript" src="<?php echo base_url().'assets/javascript/seatV2/jquery.drag_drop_multi_select_alpha-rev14safe.js'; ?>"></script>
	<script type="text/javascript" src="<?php echo base_url().'assets/javascript/seatV2/seatManipulation.js'; ?>"></script>
