				<h3 id="h_nobooking"  ><a href="#">No booking found</a></h3>
				<div id="d_nobooking">
					<div class="metrotile" id="purchaseticket" >
							<a href="<?php echo base_url(); ?>EventCtrl/book"><img src="<?php echo base_url(); ?>assets/images/metrotiles/appbar.paper2.png" alt="Purchase ticket" /></a>
					</div>
					<div style="width: 50%; float: right;">
						You don't have any bookings. Please purchase ticket(s) first.
					</div>
				</div>