<div id="basic-modal-content-dialogBox"  >
<input type="hidden" id="type" value="confirm" />
<div class="obviousContainer" >	
	<div id="crownTitle" class="okayX" ><h1>not again</h1></div>
	<div id="messageBody">		
			Are you sure you have selected all the appropriate showings?				
	</div>
	<div id="overlayEssentialButtonsArea" class="buttons" >							
							<a class="button overlayButton" id="overlayButton_YES" ><span class="icon">Yes</span></a>														
							<a class="button overlayButton" id="overlayButton_NO" ><span class="icon">No</span></a>
	</div>	
	<div id="overlayEssentialButtonsArea_OkayOnly" class="buttons" hidden="true" >							
							<a class="button overlayButton" id="overlayButton_OK" ><span class="icon">okay</span></a>																					
	</div>		
</div>
</div>