<!--
	Essential JavaScript files for Seat Map making and Seat selection
	
	*JQuery Drag, Jquery Drop plugins by Three Dub Media 2010 (c)  - http://threedubmedia.com
	 Open-source MIT license
	 
	*Excanvas by Google Inc 2006 (c)
	 Apache License v2.0
-->
<script type="text/javascript" src="<?php echo base_url();?>assets/jquery/jquery.event.drag-2.0.min.js"></script>
	<script type="text/javascript" src="<?php echo base_url();?>assets/jquery/jquery.event.drop-2.0.min.js"></script>
	<script type="text/javascript" src="<?php echo base_url();?>assets/javascript/google/excanvas.min.js"></script>